### ISSUE TITLE
Update readme to include more ways you can get Azure AD

### ISSUE THREAD

**Issue by skwan** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#15]
We should update the readme to talk about using an Azure AD you might already have, e.g. associated with your Office 365 subscription.  Plus the link below needs updating.

---

How To Run This Sample

Getting started is simple! To run this sample you will need:

Visual Studio 2013
An Internet connection
An Azure subscription (a free trial is sufficient)
Every Azure subscription has an associated Azure Active Directory tenant. If you don't already have an Azure subscription, you can get a free subscription by signing up at http://wwww.windowsazure.com. All of the Azure AD features used by this sample are available free of charge.

**Comment by danieldobalian** [comment]
Links to doc now that explains AAD tenants.  Portal link was updated.
