### ISSUE TITLE
Root Level Web.config points to https://login.mircosoftonline.com

### ISSUE THREAD

**Issue by edrohler** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#17]
This sample works after you change the ida:AADInstance value to login.windows.net{0} in the root level web.config.

**Comment by dstrockis** [comment]
Hi Eric - this is by design.  https://login.microsoftonline.com should work. What error were you seeing?

**Comment by edrohler** [comment]
I can't really recall but I think it would read that unable to access remote host login.microsoftonline.com.. Or something like that. I was using a pure MVC 4.5.2 application.

**Comment by jmprieur** [comment]
This also works with login.microsoftonline.com.
