### ISSUE TITLE
Sign Out does not work

### ISSUE THREAD

**Issue by AmitJain06** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#18]
I implement the entire code, but sign out is not working. After sign out i can access the Authorized resources.

Only 1st time sign in only required by this code , that is completely wrong.

**Comment by dinobud** [comment]
I am also having this issue. Sign out just loops back to previous page still fully authenticated. I presume it might take some sort of force clearing the sign in cookie.

**Comment by AmitJain06** [comment]
finally, I solve it... Basically it related to user role in azure active directory. For Admin user there is no need to login again and again (until browser is not closed), but other user have to sign in with its credential, every time. 


My means to say , there is no issue with the code, only user permission is the issue, for non admin user this works, as i want.
