### ISSUE TITLE
Published to azurewebsites but signout redirects the user to localhost instead of azurewebsites

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#2]
I published the sample to azurewebsites.net. Verified that the sign-on url and reply url point to azurewebsites. However, sign out redirects the user to https://localhost:44320/
Looking at the trace, https://login.windows.net/4230aed9-7637-438c-8bca-8ceaa93806f6/oauth2/logoutredirect?lc=1033 redirects to https://localhost:44320/

**Comment by swimhiking** [comment]
The testing has to be publish to Azure to work right? I try to just run in local, click login, then go to here https://localhost:44320/Account/SignIn with 400 Bad Request.

**Comment by mturscak** [comment]
Thanks for the comment, anujc. I was having the same issue and I changed the reply url to the main page url in both the portal and the web config, and that fixed the problem. Now I can log in as a user to the published web app.

**Comment by jmprieur** [comment]
Indeed, when deploying to Azure one needs to add a Reply URL in the application registration in the Azure portal.
