### ISSUE TITLE
Registering new users.

### ISSUE THREAD

**Issue by Bartmax** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#23]
It would be great if the sample have the User Registration integrated.

**Comment by dstrockis** [comment]
Hey @Bartmax. Could you elaborate?  Do you mean registering the user in the app's user store/database?  Are you referring to individual auth?

**Comment by Bartmax** [comment]
@dstrockis hey sure! Sorry for not being clear.

The examples all shown how to use the login workflow, but there's no indication in how/where to register the users or signup. I think it just a matter of redirect the user to the appropriate endpoint, what I was suggesting was to have it included on the sample.

**Comment by jmprieur** [comment]
you might want to have a look at https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp
