### ISSUE TITLE
Issue: IDX10223: Lifetime validation failed. The token is expired

### ISSUE THREAD

**Issue by johnnythinkgeo** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#25]
Hi Guys,

I downloaded the sample "active-directory-dotnet-webapp-openidconnect", and completed all the configurations mentioned at https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-webapp-dotnet/, then run it in IIS 8.5, all are pretty good, no problem. Then I keep the accessed page in Chrome for one night, and try doing a refresh the next morning, however, after input the required username and password, it runs into the following exception:

 Server Error in '/' Application.

IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '05/19/2016 10:45:59'
Current time: '05/19/2016 21:46:31'.

Anybody experienced the same problem? How can I refresh the Token? I tried doing Signout directly and changed the public address, but all doesn't work. Please help.

Thanks,
Johnny

**Comment by Martin-Yuan** [comment]
Hi Johnny,
Today i met this issue,i found the different timezone cause this issue.

**Comment by johnnythinkgeo** [comment]
wow, cool!!! I will do a check, thanks for your suggestion.

**Comment by danilocecilia** [comment]
hi @johnnythinkgeo , did you get it solve? im running on this same problem, but couldn´t find any solution yet.

**Comment by kalyankrishna1** [comment]
It usually happens if your machine's time settings are incorrect.
