### ISSUE TITLE
Single sign out - how to show a "you've been signed out" page/dialog

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#26]
There are several approaches to this, including:
- polling the service from js every few seconds to check for a valid session
- monitoring the ASP.NET session cookie from js for changes in session (requires non-HttpOnly)
- creating a second non-HttpOnly session cookie which can be monitored by js
- dropping a cookie when single sign out occurs and looking for that cookie on every server request
- dropping a cookie when single sign out occurs and looking for that cookie from js

We have yet to decide on the most widely usable approach, so for now the sample logs the user out without saying anything

**Comment by jmprieur** [comment]
You now have the "you've been signed out" page.
