### ISSUE TITLE
Azure excessive charges

### ISSUE THREAD

**Issue by tomstricker** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#27]
Anyone wind up with a billr a couple of months trial version? for $1500 ? I made the mistake of signing up for a trial version and got socked with the bill from Spectrum Consultants (India). Is this a scam?

**Comment by danieldobalian** [comment]
It's hard to say with the info provided, but linked below is the Azure AD Pricing you can use as a reference.

https://azure.microsoft.com/en-us/pricing/details/active-directory/
