### ISSUE TITLE
Hotmail account not working with azure aad

### ISSUE THREAD

**Issue by ppk112** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#28]
Hi,

I tried my Hotmail/live account, not able to authenticate but organizational account works fine. Is there anything I need to do for Hotmail or live account?

Thanks.

**Comment by danieldobalian** [comment]
In order to use a hotmail or live account you have to use the converged endpoint (v2 apps). Below is an OIDC .NET sample using v2 that should be what you need.

https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2
