### ISSUE TITLE
Refresh or access tokens persistence

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#29]
In this particular sample "**Web Browser to Web Application**" flow, do I need to worry about - Refresh tokens, storage or persistence of tokens? If yes, can you point me to right direction.

Thanks for your advise!
Sam

**Comment by danieldobalian** [comment]
This particular sample does not have persistent storage of tokens.  The sample link below stores tokens in a database and should be quite helpful.

https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-multitenant-openidconnect
