### ISSUE TITLE
One authorization for two applications

### ISSUE THREAD

**Issue by ArtemZinenko** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#34]
I use Azure AD, OpenID Connect and Microsoft.Owin for authorization users in my two ASP.NET MVC 4.X applications. Is it possible to use a common cookie for both sites and open the login popup once but not for each site?

**Comment by ArtemZinenko** [comment]
Do you have any update on this?

**Comment by mturscak** [comment]
I also would like to know about this.

**Comment by jmprieur** [comment]
Cookies are only for one domain..
