### ISSUE TITLE
Not able to  Single sign-out using the EndSession

### ISSUE THREAD

**Issue by ismail1971** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#38]
I have followed the instruction to set up the logout url for single sign out but it is not working. I have 2 apps with logout url setup. I login to the apps in the same browser tab and logout of one app but still the other app is logged in. If call the EndSession end point manually for the 2nd app then it logged out. Seems like AZURE AD is not calling the logout url automatically. Not sure if I am missing some other settings related to single sign out.

**Comment by jmprieur** [comment]
@ismail1971 for a single sign-out you might want to have a look at the following sample:
https://github.com/Azure-Samples/active-directory-dotnet-web-single-sign-out

Closing this issue as I think the question is answered
cc: @kalyankrishna1
