### ISSUE TITLE
Cannot find nugets Microsoft.Owin.Security.OpenIdConnect and Microsoft.IdentityModel.Protocol.Extensions mentioned in How to recreate this sample

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#4]
I am following step 4 in How to recreate this sample but couldn't find nugets Microsoft.Owin.Security.OpenIdConnect and Microsoft.IdentityModel.Protocol.Extensions

**Comment by jmprieur** [comment]
The sample had a .nuget folder which should no longer be here with recent versions of VS and MSBuild. It's removed things build fine now.
