### ISSUE TITLE
Always redirect to redirect_uri when click 'Create a new Microsoft account' while login

### ISSUE THREAD

**Issue by sylfree9999** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#40]
Hi,

First of all, thanks very much for the code sample. 

I am studying the WebApp-OpenIDConnect-DotNet Sample, but I found out when clicking the Create a new Microsoft account, it always redirect to the redirect_uri that I set in the web.config.
![20171010110851](https://user-images.githubusercontent.com/15099465/31367978-59dcdeb0-adad-11e7-976d-a97d0f087f72.png)

Is there any way this can redirect to Microsoft User Creation page? 

And btw, how can I capture the authentication token that Azure AD creates? Are there any tools that I can see the request/response detail? I have tried Fiddler but with no success.
![20171010111827](https://user-images.githubusercontent.com/15099465/31367945-24da5b84-adad-11e7-9641-0498518e3ea9.png)

**Comment by kalyankrishna1** [comment]
Hi, did you end up on the screenshot below using this sample? 
I have always been able to capture auth flows and tokens using fiddler. Do you have the "capture https" options checked? Fiddler root cert placed in correct container ?

**Comment by kalyankrishna1** [comment]
Reopening this as I pressed the wrong button and ended up closing this thread after asking questions :)

**Comment by jmprieur** [comment]
@sylfree9999 : closing this thread. Feel free to reopen if you want to answer Kalyan's question;
