### ISSUE TITLE
Hosting in Local IIS throws exception

### ISSUE THREAD

**Issue by pkmahapatra** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#43]
I have recreated the application and it works fine when run under IIS Express. But when it is hosted in Local IIS it throws the following exception -
![image](https://user-images.githubusercontent.com/31986903/35095048-2cb9a224-fc6d-11e7-9e7c-002fb9471f7c.png)

Please help

**Comment by pkmahapatra** [comment]
After doing some homeworks and googling I found that the reason for the above exception is due to the following -

The web server cannot communicate   with the public URL/IP address because of strong Firewall rules or the public   IP and the internal IP of the web server communicate via a proxy IP
--


Now I am not sure how to overcome this problem .....

**Comment by jmprieur** [comment]
you probably need to add rules to your firewall to let the traffic through IIS.
Closing this issue as this is not an issue with the sample.
