### ISSUE TITLE
Integrate Azure AD into a web application using OAuth 2.0

### ISSUE THREAD

**Issue by TommySharpNZ** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#45]
Hey everyone, sorry I'm looking for this exact content and examples but that shows how to use OAuth 2.0.

Anyone able to help me out with links or something???

**Comment by jmprieur** [comment]
@TommySharpNZ : OpenID Connect is a derivation of OAuth 2.0.. Whereas OAuth 2.0 does not specify the shape of the token, for instance, OpenIDConnect decides that this will be JWT.
So this is using OAuth 2.0

You can also find some more recent ASP.NET Core 2.0 samples in [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore ](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore)
