### ISSUE TITLE
Returning this error  

### ISSUE THREAD

**Issue by rashnk** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#46]
Error.We're having trouble signing you in. 
IDX21323: RequireNonce is '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated

**Comment by jmprieur** [comment]
I've just updated the sample with recent NuGet packages and tests. Closing this issue. Feel free to reopen if this has not fixed it?
