### ISSUE TITLE
Application doesn't use Microsoft.IdentityModel.Protocols.OpenIdConnect

### ISSUE THREAD

**Issue by bh3605** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#47]
This is suppose to be an example for using Microsoft.IdentityModel.Protocols.OpenIdConnect, but instead it's using OWIN. Either specify why you choose to use Owin's way or use it. Same thing with the WsFederation example. There aren't any examples of Microsoft.IdentityModel.Protocols.OpenIdConnect (or it's WsFederation equivalent) anywhere so there must be some reason you guys aren't using it. =/

**Comment by jmprieur** [comment]
The application is using ASP.NET 4.x, which leverages the ASP.NET OWIN middleware itself leveraging the Microsoft.IdentityModel.Protocols library. OWIN, in that version abstracts things. you might want to have a look to more recent implementations for instance .NET Core 2.0: https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore

**Comment by bh3605** [comment]
I'm updating a webforms app. Was gonna roll my own implementation since there's no real example of using open id and neither the mvc nor the .net core versions really translate into what needs to be accomplished.

**Comment by jmprieur** [comment]
Thanks for the update, @bh3605 
If you come-up with a solution that suits your needs (I'm not sure I understand which they are), and want to share it with others, don't hesitate to add a comment with a link to your repo in the future
