### ISSUE TITLE
Access Problem after signing in

### ISSUE THREAD

**Issue by samgithub-duplicate** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#49]
After successfully signing in a user to the app (using this Azure AD sample),  User can navigate to dashboard of "portal.azure.com"

Is there way to keep the user out of **portal.azure.com**?

**Comment by jmprieur** [comment]
@samgithub-duplicate : I don't understand the question. Can you please provide detailed repro steps?

**Comment by jmprieur** [comment]
Closing this issue as the question was not answered (and the described behavior cannot be reproed and does not make sense for the sample)
