### ISSUE TITLE
How do I Get the User Information After Signing In?

### ISSUE THREAD

**Issue by josh-monreal** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#54]
Is it possible to extract the details such as **email address** and other information stored in Azure AD for the logged in user?

**Comment by jmprieur** [comment]
@josh-monreal I suggest you have a look at the following sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2, which is more recent, and will answer these questions (typically the information is in the Principal, and you can call the Microsoft Graph to get all the information you want on the user)

**Comment by kalyankrishna1** [comment]
Closing as this issue seems resolved
