### ISSUE TITLE
How to load test app with openid connect authentication

### ISSUE THREAD

**Issue by phanikir** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#60]
Can you let us know how to configure openid connect authentication to do load test

**Comment by TiagoBrenck** [comment]
Hi, you can find some tests here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/865145b6986fa373ba916739c85fe8843ebc6d85/tests

Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC
